### ISSUE TITLE
Call to a member function getRepository() on null

### ISSUE THREAD

**Issue by harry-bennett** [coopTilleuls/CoopTilleulsForgotPasswordBundle#35]
Good afternoon vincentchalamon,

I have followed all the steps on the getting_started.md tutorial but am getting a getRepository() error. Do you know what might be causing this? 

Thank you.

Below is my Stack Trace:
`
in vendor/tilleuls/forgot-password-bundle/Manager/Bridge/DoctrineManager.php at line 37   -
    public function findOneBy($class, array $criteria)
    {
        return $this->registry->getManagerForClass($class)
            ->getRepository($class)
            ->findOneBy($criteria);
    }

at DoctrineManager ->findOneBy ('UserBundle\\Entity\\PasswordToken', array('user' => object(User))) 
in vendor/tilleuls/forgot-password-bundle/Manager/PasswordTokenManager.php at line 94   + 

at PasswordTokenManager ->findOneByUser (object(User)) 
in vendor/tilleuls/forgot-password-bundle/Manager/ForgotPasswordManager.php at line 63   + 

at ForgotPasswordManager ->resetPassword ('xxx@xxxx.test') 
in vendor/tilleuls/forgot-password-bundle/Controller/ForgotPasswordController.php at line 51   + 

at ForgotPasswordController ->resetPasswordAction ('xxx@xxxx.test') 
at call_user_func_array (array(object(ForgotPasswordController), 'resetPasswordAction'), array('xxx@xxxx.test')) 
in var/cache/dev/classes.php at line 4245   + 

at HttpKernel ->handleRaw (object(Request), 1) 
in var/cache/dev/classes.php at line 4200   + 

at HttpKernel ->handle (object(Request), 1, true) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php at line 168   + 
at Kernel ->handle (object(Request)) 
in web/app_dev.php at line 28   +
 `

**Comment by vincentchalamon** [comment]
Doctrine cannot retrieve the entity manager related to your entity `UserBundle\Entity\PasswordToken`. Maybe you've misconfigure doctrine?

**Comment by harry-bennett** [comment]
Thanks for getting back to me so quickly. 

Do I need to add anything to the User Entity? I'm also finding 'doctrine:migrations:diff' isn't creating a migration for the PasswordToken, is that normal?

Thank you.

**Comment by vincentchalamon** [comment]
Can you dump the doctrine configuration please?

**Comment by vincentchalamon** [comment]
Here is a example of doctrine & coop_tilleuls_forgot_password on a Symfony 4 project using Flex:
```yaml
# config/packages/doctrine.yaml
doctrine:
    dbal:
        # ...
    orm:
        # ...
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

# config/packages/coop_tilleuls_forgot_password.yaml
coop_tilleuls_forgot_password:
    password_token:
        class: App\Entity\PasswordToken # required
        expires_in: 1 day
        user_field: user
        serialization_groups: []
    user:
        class: App\Entity\User # required
        email_field: email
        password_field: password
```
