### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by harry-bennett** [coopTilleuls/CoopTilleulsForgotPasswordBundle#45]
Good morning Vincent,

I'm trying to install this package but seem to be having some problems. I have the following in my config.yml

```
coop_tilleuls_forgot_password:`
    password_token:
        class: UserBundle\Entity\PasswordToken  # required
        expires_in: 1 day
        user_field: user
        serialization_groups: []
    user:
        class: UserBundle\Entity\User # required
        email_field: email
        password_field: password
    use_jms_serialize: false # Switch between symfony's serializer component or JMS Serializer
```

This seems to give me the error 'Unrecognized option "use_jms_serialize" under "coop_tilleuls_forgot_password'.

I've then commented out the 'use_jms_serialize' attribute. This then results me in getting another error 
'TypeError: Argument 1 passed to CoopTilleuls\ForgotPasswordBundle\Normalizer\SymfonyNormalizer::__construct() must implement interface Symfony\Component\Serializer\Normalizer\NormalizerInterface, instance of JMS\Serializer\Serializer given, called in ..../appTestDebugProjectContainer.php on line 2709'

Do you have any idea why this config is not getting accepted?

Thank you 

Harry
