### ISSUE TITLE
Cannot define a custom manager in Symfony 5.1

### ISSUE THREAD

**Issue by tumbochka** [coopTilleuls/CoopTilleulsForgotPasswordBundle#62]
Steps:

1. Implement a custom manager (mongo document manager in my case but it doesn't matter).
2. Define it in the services
```
    mongo.persister:
        class: App\Doctrine\MongoPersister
        public: true
        arguments: [ '@doctrine_mongodb.odm.default_document_manager']
```
3. Use it in the config
```
coop_tilleuls_forgot_password:
    manager: mongo.persister
    password_token:
....
```
4. Clear the cache and get the exception.
```
root@c28c46157c96:/auth_service# bin/console cache:clear                    

In CoopTilleulsForgotPasswordExtension.php line 58:
                                             
  Service "mongo.persister" does not exist.  
```

The reason of the issue is that the Symfony 5.1 uses a temporary container   for the extension initializing and merges in to the main container after initializing. The temporary container doesn't have the previously initialized services.

Solution: remove the check from the extension:
```
        if (!$container->hasDefinition($config['manager'])) {
            throw new \LogicException(sprintf('Service "%s" does not exist.', $config['manager']));
        }

```
