### ISSUE TITLE
Why does `GET /forgot_password/{tokenValue}` return the entire user?

### ISSUE THREAD

**Issue by CodeCasterNL** [coopTilleuls/CoopTilleulsForgotPasswordBundle#81]
The `GET /forgot_password/{tokenValue}` controller ultimately calls `NormalizerInterface->normalize($token, ...)`, which, through Doctrine's lazy loading and Symfony's normalizer, serializes the entire User entity as JSON.

This seems unnecessary, we just need to know whether the token is valid. Why does it instead serialize the entire user?

The reason for this issue is that this throws in our setup: we have Ramsey UUIDs for all our entities, and the serializer complains about the binary representing our user's ID not being valid UTF-8, which indeed it isn't:

> Malformed UTF-8 characters, possibly incorrectly encoded

In vendor/symfony/http-foundation/JsonResponse.php.

The workaround is a custom normalizer:

```
class PasswordTokenNormalizer implements NormalizerInterface
{
    /**
     * @param AbstractPasswordToken $object
     */
    public function normalize($object, $format = null, array $context = []): array
    {
        return [
            'isExpired' => $object->isExpired(),
        ];
    }

    public function supportsNormalization($data, $format = null): bool
    {
        return $data instanceof AbstractPasswordToken;
    }
}
````

Or a serialization group configuration:

```
coop_tilleuls_forgot_password:
    password_token:
        class: App\Entity\PasswordToken
        expires_in: 1 day
        user_field: user
        serialization_groups: [ 'forgotpassword:read' ]
```

```
App\Entity\PasswordToken:
  attributes:
    isExpired:
      groups:
        - 'forgotpassword:read'

```

Can it perhaps be documented what the endpoints do?
