### ISSUE TITLE
Hardcoded paths

### ISSUE THREAD

**Issue by Cruiser13** [coopTilleuls/CoopTilleulsForgotPasswordBundle#93]
**Describe the bug**
Both Bridge/ApiPlatform/OpenApi/OpenApiFactory.php and Bridge/ApiPlatform/Serializer/DocumentationNormalizer.php use hardcoded paths to /forgot-password/and /forgot-password/{token}

**To Reproduce**
Use a routing like this:
```yaml
coop_tilleuls_forgot_password:
  resource: "@CoopTilleulsForgotPasswordBundle/Resources/config/routing.xml"
  prefix:   /api/forgot_password
```

**Expected behavior**
The bundle works at /api/forgot_password

**Actual behavior**
The routing is set to /api/forgot_password but the docs are still leading to /forgot-password/and /forgot-password/{token}
While it's possible to set the proper routes using OpenApi in application it seems to be not possible to remove the routes set by the bundle.

**Proposed fix**
Use prefix instead of hardcoded route in Bridge/ApiPlatform/OpenApi/OpenApiFactory.php and Bridge/ApiPlatform/Serializer/DocumentationNormalizer.php
